#1. Basic Exploration
Load the dataset into a Pandas DataFrame. Display:
○ The first 10 rows
○ The total number of rows and columns
○ Summary statistics for numerical columns

In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv('/content/auto-mpg.csv')

In [ ]:
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [ ]:
df.shape # shape

(398, 9)

In [ ]:
df.describe() #summary statistics

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

#2. Filtering and Indexing
Find all cars manufactured in 1975 with a weight less than 3000. Return the
DataFrame with selected columns: car_name, weight, and mpg.

In [ ]:
df[(df['model year'] == 75) & (df['weight'] < 3000)][['car name', 'weight', 'mpg']]

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [ ]:
df[['car name', 'weight', 'mpg']]

                      car name  weight   mpg
0    chevrolet chevelle malibu    3504  18.0
1            buick skylark 320    3693  15.0
2           plymouth satellite    3436  18.0
3                amc rebel sst    3433  16.0
4                  ford torino    3449  17.0
..                         ...     ...   ...
393            ford mustang gl    2790  27.0
394                  vw pickup    2130  44.0
395              dodge rampage    2295  32.0
396                ford ranger    2625  28.0
397                 chevy s-10    2720  31.0

[398 rows x 3 columns]

#3. Handling Missing Data
Identify if there are any missing values in the dataset. Replace missing values in the
horsepower column with the column's median.

In [9]:
import pandas as pd
df =pd.read_csv('/content/auto-mpg.csv')
# Check missing values
print(df.isna().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [10]:
# Convert to numeric (handle '?')
df['horsepower']=pd.to_numeric(df['horsepower'],errors='coerce')

In [11]:
# Check again the missing values
print(df.isna().sum())

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [12]:
# Find Median
median_hp=df['horsepower'].median()
print(median_hp)

93.5

In [13]:
# Fill missing values with Median
df['horsepower']=df['horsepower'].fillna(median_hp)

In [14]:
# Verify
print(df.isna().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

# 4.Data Transformation
Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [ ]:
df =pd.read_csv('/content/auto-mpg.csv')

In [ ]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [ ]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']

In [ ]:
print(df[['horsepower', 'weight', 'power_to_weight_ratio']].head())

   horsepower  weight  power_to_weight_ratio
0       130.0    3504               0.037100
1       165.0    3693               0.044679
2       150.0    3436               0.043655
3       150.0    3433               0.043694
4       140.0    3449               0.040591

#5. Group By
Group the cars by origin and calculate the mean mpg for each group.

In [ ]:
grouped_mpg = df.groupby('origin')['mpg'].mean()
print(grouped_mpg)

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

#6.Sorting
Sort the DataFrame by mpg in descending order and display the top 10 cars with
the highest mpg.

In [ ]:
top_10_mpg = df.sort_values(by='mpg', ascending=False).head(10)
print(top_10_mpg[['car name', 'mpg']])

                            car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4

#7. Apply this function to each row and store the result in the new column.

In [ ]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

In [ ]:
df['performance_score'] = df.apply(performance_score, axis=1)

In [ ]:
print(df[['mpg', 'acceleration', 'weight', 'performance_score']].head())

    mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754

#8. Visualization Preparation
Generate a summary DataFrame with:
○ Average mpg, weight, and horsepower for each model_year.

In [15]:
# Group and Aggregate
summary_df=df.groupby('model year')[['mpg','weight','horsepower']].mean()

In [16]:
print(summary_df)

                  mpg       weight  horsepower
model year
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

#9. Exporting Data
Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [17]:
# Filter Data
filtere_df=df[df['mpg']>30]

In [19]:
# Select Columns
subset=filtere_df[['mpg','cylinders','horsepower','weight']]

In [20]:
# Export to CSV
subset.to_csv('high_mpg_cars.csv',index=False)

#10. Finding Anomalies
Identify potential outliers in the mpg column using the Interquartile Range (IQR)
method. Specifically:
● Calculate the IQR for mpg.
● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.
● Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
# and model_year.

In [ ]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

In [ ]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [ ]:
outliers = df[(df['mpg'] < lower_bound) | (df['mpg'] > upper_bound)]

In [ ]:
outliers_df = outliers[['car name', 'mpg', 'model year']]
print(outliers_df)

      car name   mpg  model year
322  mazda glc  46.6          80

#NumPy

#1. Basic Array Operations
Convert the mpg column into a NumPy array and calculate:
○ The mean, median, and standard deviation of mpg.
○ The number of cars with mpg greater than 25.

In [ ]:
import numpy as np

data = df.values

In [ ]:
mpg_array = df['mpg'].to_numpy()

mean_mpg = np.mean(mpg_array)
median_mpg = np.median(mpg_array)
std_mpg = np.std(mpg_array)

count_above_25 = np.sum(mpg_array > 25)

print(mean_mpg, median_mpg, std_mpg, count_above_25)

23.514572864321607 23.0 7.806159061274433 158

#2. Filtering
Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list.

In [ ]:
cyl_array = df['cylinders'].to_numpy()
car_names = df['car name'].to_numpy()

filtered_cars = car_names[cyl_array > 6]

print(filtered_cars.tolist())

['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino', 'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii', 'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se', "plymouth 'cuda 340", 'chevrolet monte carlo', 'buick estate wagon (sw)', 'ford f250', 'chevy c20', 'dodge d200', 'hi 1200d', 'chevrolet impala', 'pontiac catalina brougham', 'ford galaxie 500', 'plymouth fury iii', 'dodge monaco (sw)', 'ford country squire (sw)', 'pontiac safari (sw)', 'chevrolet impala', 'pontiac catalina', 'plymouth fury iii', 'ford galaxie 500', 'amc ambassador sst', 'mercury marquis', 'buick lesabre custom', 'oldsmobile delta 88 royale', 'chrysler newport royal', 'amc matador (sw)', 'chevrolet chevelle concours (sw)', 'ford gran torino (sw)', 'plymouth satellite custom (sw)', 'buick century 350', 'amc matador', 'chevrolet malibu', 'ford gran torino', 'dodge coronet custom', 'mercury marquis brougham', 'chevrolet caprice classic', 'ford ltd', 'plymouth fury gran sedan', 'chrysler new yorker brougham', 'buick electra 225 custom', 'amc ambassador brougham', 'chevrolet impala', 'ford country', 'plymouth custom suburb', 'oldsmobile vista cruiser', 'chevrolet monte carlo s', 'pontiac grand prix', 'dodge dart custom', 'oldsmobile omega', 'ford gran torino', 'buick century luxus (sw)', 'dodge coronet custom (sw)', 'ford gran torino (sw)', 'amc matador (sw)', 'pontiac catalina', 'chevrolet bel air', 'plymouth grand fury', 'ford ltd', 'chevrolet monza 2+2', 'ford mustang ii', 'chevrolet chevelle malibu classic', 'dodge coronet brougham', 'amc matador', 'ford gran torino', 'plymouth volare premier v8', 'cadillac seville', 'chevy c10', 'ford f108', 'dodge d100', 'chevrolet caprice classic', 'oldsmobile cutlass supreme', 'dodge monaco brougham', 'mercury cougar brougham', 'pontiac grand prix lj', 'chevrolet monte carlo landau', 'chrysler cordoba', 'ford thunderbird', 'oldsmobile cutlass salon brougham', 'dodge diplomat', 'mercury monarch ghia', 'chevrolet monte carlo landau', 'ford futura', 'dodge magnum xe', 'chevrolet caprice classic', 'ford ltd landau', 'mercury grand marquis', 'dodge st. regis', 'buick estate wagon (sw)', 'ford country squire (sw)', 'chevrolet malibu classic (sw)', 'chrysler lebaron town @ country (sw)', 'cadillac eldorado', 'oldsmobile cutlass salon brougham', 'oldsmobile cutlass ls']

#3. Statistical Analysis
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [ ]:
weight_array = df['weight'].to_numpy()

percentiles = np.percentile(weight_array, [25, 50, 75])

print(percentiles)

[2223.75 2803.5  3608.  ]

#4. Array Manipulation
Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [21]:
# Find Column Indexes
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [23]:
# Extract Column
acc_array = df['acceleration'].to_numpy()

In [24]:
# Compute Min and Max
min_val=np.min(acc_array)
max_val=np.max(acc_array)

In [25]:
# Normalize
normalized_acc=(acc_array-min_val)/(max_val-min_val)

In [26]:
# first 10 values
print(normalized_acc[:10])

[0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619 ]

#5. Broadcasting
Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.

In [28]:
# Find Column Indexes
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [31]:
# Extract Horsepower Column
hp_array = df['horsepower'].to_numpy()

In [32]:
# Handle missing values
# Convert hp_array to numeric first, coercing non-numeric values to NaN
hp_array = pd.to_numeric(hp_array, errors='coerce')
# Now np.isnan can be applied
np.isnan(hp_array).sum()
np.int64(0)

np.int64(0)

In [33]:
# Replace missing values with Mean
mean_hp=np.nanmean(hp_array)
hp_array=np.where(np.isnan(hp_array),mean_hp,hp_array)

In [34]:
# Apply 10% Increase (Broadcasting)
updated_hp=hp_array*1.10

In [35]:
print(updated_hp[:10])

[143.  181.5 165.  165.  154.  217.8 242.  236.5 247.5 209. ]

#6. Boolean Indexing
Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing.

In [ ]:
origin_array = df['origin'].to_numpy()
disp_array = df['displacement'].to_numpy()

avg_disp_europe = np.mean(disp_array[origin_array == 2])

print(avg_disp_europe)

109.14285714285714

#7. Matrix Operations
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [36]:
# Find Column Indexes
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [39]:
df_np = df.to_numpy()
# Create Matrix
matrix=df_np[:,[0,3,4]]

In [40]:
# Define Vector
vector=np.array([1,0.5,-0.2])

In [41]:
# Dot Product
result=np.dot(matrix, vector)

In [42]:
# first 10 values
print(result[:10])

[-617.8000000000001 -641.1 -594.2 -595.6 -602.8000000000001 -754.2
 -746.8000000000001 -740.9000000000001 -758.5 -660.0]

#8. Sorting
Use NumPy to sort the cars by model_year in descending order and display the first
f
ive car names.

In [43]:
# Find Column Indexes
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [44]:
# Extract Columns
model_year=df_np[:,6]
car_names=df_np[:,8]

In [45]:
# Get Sorted Indices
sorted_indices=np.argsort(model_year)

In [46]:
# Reverse for Descending
sorted_indices=sorted_indices[::-1]

In [47]:
# Get Top 5 Car Names
top_5_cars=car_names[sorted_indices][:5]

In [48]:
print(top_5_cars)

['chevy s-10' 'honda accord' 'ford ranger' 'chevrolet cavalier'
 'chevrolet cavalier wagon']

#9. Correlation
Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [ ]:
mpg_array = df['mpg'].to_numpy()
weight_array = df['weight'].to_numpy()

correlation = np.corrcoef(mpg_array, weight_array)[0, 1]

print(correlation)

-0.8317409332443352

#10. Conditional Aggregates
Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [49]:
# Find Column Indexes
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [50]:
# Extract Columns
mpg = df_np[:, 0].astype(float)
cylinders = df_np[:, 1].astype(int)

In [51]:
# Get Unique Cylinder Values
unique_cyl = np.unique(cylinders)

In [53]:
# Loop and Compute Mean
for cyl in unique_cyl:
    mask = cylinders == cyl
    avg_mpg = np.mean(mpg[mask])
    print(f"Cylinders: {cyl}, Avg MPG: {avg_mpg}")

Cylinders: 3, Avg MPG: 20.55
Cylinders: 4, Avg MPG: 29.28676470588235
Cylinders: 5, Avg MPG: 27.366666666666664
Cylinders: 6, Avg MPG: 19.985714285714284
Cylinders: 8, Avg MPG: 14.963106796116506